### ISSUE TITLE
Corrigir as provas sendo utilizadas

### ISSUE THREAD

**Issue by leonardotkimura** [larc-logs-transparentes/tlverifier#1]
Na linha [aqui ](https://github.com/larc-logs-transparentes/tlverifier/blob/f0015d9807ac5f5eaa836489ff391c5cb7e8ab72/src/tlverifier/merkle_functions/tl_functions.py#L46), corrigir para:

```
    local_proof = proof["data"]["inclusion_proof"]
    global_proof = proof["local_tree"]["inclusion_proof"]
```

**Comment by hellkha** [comment]
O server foi alterado para enviar os dados de "data" e de "local_tree" nas posições corretas?
Porque simplesmente inverter isso sem corrigir na fonte de dado vai retornar False no verify_single_data.

**Comment by hellkha** [comment]
Substituição feita
