### ISSUE TITLE
Expor os métodos 'get_proof' e outros

### ISSUE THREAD

**Issue by leonardotkimura** [larc-logs-transparentes/tlverifier#2]
expor os métodos 'get_proof', 'get_global_root', e outros, para poder ser utilizado fora do módulo.

E.g., from tlverifier.merkle_functions.data_access import get_proof,

proof = get_proof().

Sugestão: renomear as funções. 'get_dummy_proof', 'get_mocked_proof', ou coisa parecida.

**Comment by hellkha** [comment]
Adicionado:
from .merkle_functions.tl_functions import *
from .merkle_functions.data_access import *

a:
src/tlverifier/__init__.py

agora funciona assim:
import tlverifier
result = tlverifier.verify_single_data(...)
