### ISSUE TITLE
Remover a conversão 'bytes' para as provas

### ISSUE THREAD

**Issue by leonardotkimura** [larc-logs-transparentes/tlverifier#3]
remover todas as conversões para 'bytes' para as provas (e.g., [aqui](https://github.com/larc-logs-transparentes/tlverifier/blob/7d913ec6b618938700b907fd33156136f63ec864/src/tlverifier/merkle_functions/tl_functions.py#L42)).

Foi alterado correspondentemente no tlmanager [pr-28](https://github.com/larc-logs-transparentes/logs-transparentes/pull/28)

**Comment by hellkha** [comment]
Alterado e subido, antes de fechar a issue, por favor realize alguns testes com os dados atuais do servidor usando a versão 0.0.24 da lib: https://test.pypi.org/project/tlverifier/0.0.24/

**Comment by leonardotkimura** [comment]
Só faltou tirar a linha https://github.com/larc-logs-transparentes/tlverifier/blob/4c5557d773b95e2a17a86eb87d737d918eda0e38/src/tlverifier/merkle_functions/tl_functions.py#L94. Feito isso, o teste funciona perfeito :)

**Comment by hellkha** [comment]
Alteração realizada
